// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FavouriteButtonController from "./favourite_button_controller"
application.register("favourite-button", FavouriteButtonController)

import GetDirectionsController from "./get_directions_controller"
application.register("get-directions", GetDirectionsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ScriptController from "./script_controller"
application.register("script", ScriptController)

import SocialShareButtonController from "./social_share_button_controller"
application.register("social-share-button", SocialShareButtonController)
